services:
  doi-fetcher:
    build: .
    container_name: doi-fetcher
    volumes:
      - ./data/papers-data.json:/app/data/papers-data.json    # Mounts specified folder from path into ./data
      - ./input.txt:/app/input.txt                            # Mounts the local input.txt
    working_dir: /app
    stdin_open: true                         # Needed for nano
    tty: true                                # Allows interactive terminal usage
    command: npm start                       # Optional override, but already set in Dockerfile